### ISSUE TITLE
希望可以增加一个是否生成字段注释的选项

### ISSUE THREAD

**Issue by fengpojian** [moshowgame/SpringBootCodeGenerator#100]
首先感谢作者，这是个非常好用的工具。
在使用过程中，感觉自动生成字段注释的功能的有些鸡肋。有些字段非常简单就没有在mysql中添加注释，但是工具就会默认字段名注释。生成完之后还要一个个的删除。
建议增加一个是否需要字段注释的选项。

**Comment by moshowgame** [comment]
sure。新版考虑加入该选项。

**Comment by moshowgame** [comment]
3.0版本已增加该选项，感谢反馈，thanks！
