### ISSUE TITLE
建议新增去除表名前缀选项

### ISSUE THREAD

**Issue by wwlg** [moshowgame/SpringBootCodeGenerator#102]
@moshowgame 只是个建议
//去除表前缀
  if (tableName.contains(tablePrefix)){
      tableName = tableName.replace(tablePrefix, "");
  }

**Comment by moshowgame** [comment]
good idea. 新版即将加上该选项

**Comment by moshowgame** [comment]
3.0版本已增加该选项，感谢反馈，thanks！
