### ISSUE TITLE
mybatis-plus的代码为何Controller直接调用了Mapper?

### ISSUE THREAD

**Issue by feng99** [moshowgame/SpringBootCodeGenerator#134]
1.mybatis-plus的代码为何Controller直接调用了Mapper?

那Service的代码  作用是什么?

2.Service 接口,为何没有实现类

3.我在Controller类中引入Service类
private final OmsOrderLogisticsService omsOrderLogisticsService;

启动时报错
Parameter 0 of constructor in com.macro.mall.controller.OmsOrderLogisticsController required a bean of type 'com.macro.mall.service.OmsOrderLogisticsService' that could not be found.

**Comment by moshowgame** [comment]
1.controller是可以call service和mapper的，看需求。懒人的做法就是直接call mapper。复杂一些的逻辑在service进行封装
2.service中的GeneratorServiceImpl就是实现类
3.你引入的类可能是类本身有错误，或者没有@Controller/@RestController注解导致无法识别等原因。通常建议直接@Autowired引入service即可，不要去final和做其他设定
