### ISSUE TITLE
老哥，JDK版本改到11在idea中运行报错“java: Compilation failed: internal java compiler error”

### ISSUE THREAD

**Issue by complexjeck** [moshowgame/SpringBootCodeGenerator#147]
我的IDEA版本是2023.1.3
java版本：
E:\software_workspace\idea_workspace\code-generator\SpringBootCodeGenerator>java -version
java version "11.0.20" 2023-07-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.20+9-LTS-256)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.20+9-LTS-256, mixed mode)

Maven版本：
E:\software_workspace\idea_workspace\code-generator\SpringBootCodeGenerator>mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T02:41:47+08:00)
Maven home: C:\Program Files\apache-maven-3.6.0\bin\..
Java version: 11.0.20, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

IDEA运行报错：
![image](https://github.com/moshowgame/SpringBootCodeGenerator/assets/26809241/8698f4b3-9079-41e8-bba4-4675ab822d87)

折腾了一晚上了，难受。

**Comment by complexjeck** [comment]
还得得回归到旧版本才行，最新的可能要JDK17才能运行
git checkout 8f4e09d

**Comment by CyberHunter775** [comment]
jdk换成17就行了

**Comment by moshowgame** [comment]
jdk换成17就行了

**Comment by moshowgame** [comment]
老哥，新版本需要JDK17以上的哦。如果要使用旧版本，可以手工回滚到https://github.com/moshowgame/SpringBootCodeGenerator/commit/8f4e09d01a782366188e1df3b4c680b43214ef0a

**Comment by moshowgame** [comment]
https://github.com/moshowgame/SpringBootCodeGenerator/tree/jdk11
JDK11分支可以有效支持JDK11，但是可能功能上会相对落后一点
