### ISSUE TITLE
ReturnT那个工具类可以发一下吗

### ISSUE THREAD

**Issue by niocoders** [moshowgame/SpringBootCodeGenerator#16]
ReturnT那个工具类可以发一下吗谢谢

**Comment by moshowgame** [comment]
你说的是哪个个ReturnT？能给出代码的地方吗，，这是开源项目，都开源了。。。工具类一般是在https://github.com/moshowgame/SpringBootCodeGenerator/tree/master/generator-web/src/main/java/com/softdev/system/generator/util
