### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by MrXionGe** [moshowgame/SpringBootCodeGenerator#19]
您好，很喜欢咱们的工具，我记得之前我们提供生成实体的时候，类型是基本类型或包装类型的选项。新版本没有找到呢？而且应该是推荐使用包装类的吧

**Comment by lfengzhang** [comment]
这个问题我也发现了，春节准备抽空优化一下这部分，到时候发pr看作者合不合并了😄

**Comment by moshowgame** [comment]
> 您好，很喜欢咱们的工具，我记得之前我们提供生成实体的时候，类型是基本类型或包装类型的选项。新版本没有找到呢？而且应该是推荐使用包装类的吧

对的。理论上是包装类型才对。那的抽空修复一下

**Comment by moshowgame** [comment]
> 这个问题我也发现了，春节准备抽空优化一下这部分，到时候发pr看作者合不合并了😄

GOOD。等待你的PR哦。。。上次有个兄台PR，，提交了太多东西，冲突严重，，搞的我都无法在线处理，，尴尬的。。。知不知道怎么处理那种情况

**Comment by lfengzhang** [comment]
> > 这个问题我也发现了，春节准备抽空优化一下这部分，到时候发pr看作者合不合并了😄
> 
> GOOD。等待你的PR哦。。。上次有个兄台PR，，提交了太多东西，冲突严重，，搞的我都无法在线处理，，尴尬的。。。知不知道怎么处理那种情况

遇到这种情况github这边的推荐是直接拒绝，让提交pr的人处理完冲突再提重新提交的，好像没啥特别好的办法

**Comment by MrXionGe** [comment]
> 这个问题我也发现了，春节准备抽空优化一下这部分，到时候发pr看作者合不合并了😄

我觉得过年应该好好休息

**Comment by lfengzhang** [comment]
> > 这个问题我也发现了，春节准备抽空优化一下这部分，到时候发pr看作者合不合并了😄
> 
> 我觉得过年应该好好休息

哈哈哈，已经准备年后跑路，找新东家了，所以过年得强迫自己做点事儿，而且现在不用包装类的确有坑，因为生成的mybatis xml 默认不带jdbctype（其实mybatis3以后带了也没用），会导致insert null值的时候setting param报错，不修不好用😄

**Comment by moshowgame** [comment]
GOOD。开工大吉，跳槽成功！

**Comment by MrXionGe** [comment]
@moshowgame   老哥，我看到你GitHub的更新记录了，但是http://java.bejson.com/generator/ 上的生成器貌似还没有更新你的版本，我刚刚试了一下，实体还是基本类型

**Comment by moshowgame** [comment]
> @moshowgame 老哥，我看到你GitHub的更新记录了，但是http://java.bejson.com/generator/ 上的生成器貌似还没有更新你的版本，我刚刚试了一下，实体还是基本类型

嗯，是的，bejson官方更新没那么快，，我通知下三叔吧。
