### ISSUE TITLE
字段可以维持SQL脚本的命名嘛

### ISSUE THREAD

**Issue by hjjoe1213123** [moshowgame/SpringBootCodeGenerator#20]
字段可以维持SQL脚本的命名嘛 ,比如“Id” 不要变成 “id”

**Comment by moshowgame** [comment]
> 字段可以维持SQL脚本的命名嘛 ,比如“Id” 不要变成 “id”

你好，这个不好说，因为本身sql脚本的命名也是要规范的，例如实体的userId代表的是user_id。所以维持SQL脚本的命名还不是特别好搞，现在是根据符号来的，统一转换成小写，然后再根据规则转换。
