### ISSUE TITLE
mybatis的dao接口，里面的pageListCount方法不用offset和pagesize了

### ISSUE THREAD

**Issue by Archer-Wen** [moshowgame/SpringBootCodeGenerator#24]
mybatis的dao接口，里面的pageListCount方法不用offset和pagesize了，xml里面计算分页的数量不需要limit分页

**Comment by moshowgame** [comment]
对了亲，能否提供一下你日常用到的模板，包括你说的pageListCount方法，，因为我也是用的jpa+mybatis plus。，，缺少mybatis相关的

**Comment by Archer-Wen** [comment]
之前一直没有上git，没有看见，关于那个文件，你可以看看我基于你的项目修改后的东西，
[https://github.com/Archer-Wen/SpringBootCodeGenerator/tree/master/generator-web/src/main/resources/templates/code-generator/mybatis](传送门)，

主要是mybatis那个模板的pageListCount()方法，然后我将你的update和insert语句修改成了有if判断的动态语句，主要是模范官方generator的

**Comment by moshowgame** [comment]
> 之前一直没有上git，没有看见，关于那个文件，你可以看看我基于你的项目修改后的东西，
> [https://github.com/Archer-Wen/SpringBootCodeGenerator/tree/master/generator-web/src/main/resources/templates/code-generator/mybatis](%E4%BC%A0%E9%80%81%E9%97%A8)，
> 
> 主要是mybatis那个模板的pageListCount()方法，然后我将你的update和insert语句修改成了有if判断的动态语句，主要是模范官方generator的

完全没问题，欢迎提出pull request~
