### ISSUE TITLE
oracle 注释不能添加在实体类里面默认是表字段

### ISSUE THREAD

**Issue by liukex** [moshowgame/SpringBootCodeGenerator#26]
CREATE TABLE "RKSJ_POPULATION_INFO" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "BSRK" NUMBER(11) COMENT '用户名',
  "LRRK" NUMBER(11) ,
  "LRRKZB" NUMBER(3,1) ,
  "LRRKTB" CHAR(1 BYTE) ,
  "LCRK" NUMBER(11) ,
  "LCRKZB" NUMBER(3,1) ,
  "LCRKTB" CHAR(1 BYTE) 
);
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."ID" IS '主表唯一标示';
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."BSRK" IS '本市人口';
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."LRRK" IS '流入人口';
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."LRRKZB" IS '流入人口占比';
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."LRRKTB" IS '流入人口同比增长还是下降（0:下降 1:增长）';
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."LCRK" IS '流出人口';
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."LCRKZB" IS '流出人口占比';
COMMENT ON COLUMN "RKSJ_POPULATION_INFO"."LCRKTB" IS '流出人口同比增长还是下降（0:下降 1:增长）';

**Comment by liukex** [comment]
注释不能用

**Comment by moshowgame** [comment]
感谢反馈，，20190429版本已经解决，谢谢！

**Comment by liukex** [comment]
新版怎么访问？
