### ISSUE TITLE
这段sql库存字段没生成出来

### ISSUE THREAD

**Issue by AhHeadFloating** [moshowgame/SpringBootCodeGenerator#27]
CREATE TABLE `b2c_sku` (
  `SKU_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'SKUID',
  `TITLE` varchar(64) DEFAULT NULL COMMENT '标题',
  `ITEM_ID` int(11) DEFAULT NULL COMMENT '商品ID',
  `PRICE` decimal(14,2) DEFAULT NULL COMMENT '售价',
  `COST_PRICE` decimal(14,2) DEFAULT NULL COMMENT '成本价',
  `MARKET_PRICE` decimal(14,2) DEFAULT NULL COMMENT '市场价',
  `SKU_STORAGE` int(11) DEFAULT NULL COMMENT '库存',
  `SKU_STORAGE_WARN` int(11) DEFAULT NULL COMMENT '库存预警值',
  `SKU_SALE_NUM` int(11) DEFAULT '0' COMMENT '销售量',
  `SKU_SERIAL` varchar(32) DEFAULT NULL COMMENT '商品编号',
  `BARCODE` varchar(32) DEFAULT NULL COMMENT '条形码',
  `WEIGHT` decimal(10,2) DEFAULT NULL COMMENT '重量',
  `SPEC_NAME` text COMMENT '规格名称',
  `SPEC_VALUE` text COMMENT '规格值',
  `STATE` char(1) DEFAULT NULL COMMENT 'SKU状态',
  `CREATE_TIME` bigint(11) DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` bigint(11) DEFAULT NULL COMMENT '修改时间',
  `IS_DELETE` tinyint(1) DEFAULT NULL COMMENT '是否删除  0:正常 1:删除',
  `CRECORD` varchar(64) DEFAULT NULL COMMENT '海关备案号',
  `IRECORD` varchar(64) DEFAULT NULL COMMENT '商检备案号',
  `HS` varchar(64) DEFAULT NULL COMMENT 'HS编码',
  `SKU_IMAGE` varchar(255) DEFAULT '0' COMMENT '规格图片',
  `MEMBER_PRICE` decimal(14,2) DEFAULT NULL COMMENT '会员价 ',
  PRIMARY KEY (`SKU_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='商品规格表';

**Comment by moshowgame** [comment]
感谢反馈，，20190429版本已经解决，谢谢！
