### ISSUE TITLE
生成java实体建议加swagger注释

### ISSUE THREAD

**Issue by chenzhixigh** [moshowgame/SpringBootCodeGenerator#28]
生成java实体建议加swagger注释

**Comment by moshowgame** [comment]
你好，能否提供一下模板

**Comment by chenzhixigh** [comment]
你是？在哪个网站上看到的？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Moshow郑锴 <notifications@github.com&gt;
发送时间: 2019年11月15日 00:00
收件人: moshowgame/SpringBootCodeGenerator <SpringBootCodeGenerator@noreply.github.com&gt;
抄送: chenzhixigh <1521941356@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[moshowgame/SpringBootCodeGenerator] 生成java实体建议加swagger注释 (#28)




你好，能否提供一下模板

**Comment by wangshihaowangbing** [comment]
同样建议，生成的javabean，加上swagger注释 apimodel apimodelproperty

**Comment by moshowgame** [comment]
> 同样建议，生成的javabean，加上swagger注释 apimodel apimodelproperty

能否提供一下模板，谢谢！简单提供一下就可以了

**Comment by moshowgame** [comment]
新版JPA的entity已经提供该功能，感谢反馈！
