### ISSUE TITLE
字段userName这种没有转换成驼峰的形式

### ISSUE THREAD

**Issue by jswfly** [moshowgame/SpringBootCodeGenerator#31]
字段userName这种没有转换成驼峰的形式
![image](https://user-images.githubusercontent.com/26086558/58605994-6327c200-82cc-11e9-86fb-ce543b4a5d7f.png)

**Comment by moshowgame** [comment]
你好，因为从数据库设计规范来讲，一般不建议驼峰，驼峰会引发歧义，userName默认代表的是user_name字段，所以没有做驼峰字段的支持。

**Comment by moshowgame** [comment]
20190909版本已经添加是否下划线转换为驼峰的选择（感谢@youngking28 的pull request）
