### ISSUE TITLE
默认生成MyBatis的xml文件对Oracle不友好

### ISSUE THREAD

**Issue by wylove1992** [moshowgame/SpringBootCodeGenerator#32]
默认生成MyBatis的xml文件中字段都是带上这个符号的`，但是这个符号oracle压根不支持！

**Comment by moshowgame** [comment]
20190910 | 1.修复mapper接口load方法，但是xml中方法不匹配问题 2.移除mapper中CRUD时的@param 注解，会影响xml的解析（感谢@caojiantao的反馈）。3.优化MyBatis的xml文件对Oracle的支持。（感谢@wylove1992的反馈） 4.新增对boolean的处理（感谢@violinxsc的反馈）以及优化tinyint类型生成boolean类型问题（感谢@hahaYhui的反馈）
-- | --
