### ISSUE TITLE
在此项目基础上添加了点小功能

### ISSUE THREAD

**Issue by gaohanghang** [moshowgame/SpringBootCodeGenerator#33]
项目地址：https://github.com/hacker-and-painter/spring-boot-code-generator

### bean get set
项目中经常会遇到需要 get bean 所有属性和 set bean 所有属性的情况，添加此功能方便开发

![](https://raw.githubusercontent.com/gaohanghang/images/master/img20190707212234.png)

### SQL
使用Navicat 通常需要写select、insert、update、delete语句，比较麻烦，使用此功能只需要填充数据即可使用

![](https://raw.githubusercontent.com/gaohanghang/images/master/img20190707212624.png)

![](https://raw.githubusercontent.com/gaohanghang/images/master/img20190707212703.png)

![](https://raw.githubusercontent.com/gaohanghang/images/master/img20190707212728.png)

![](https://raw.githubusercontent.com/gaohanghang/images/master/img20190707212756.png)

**Comment by moshowgame** [comment]
^_^欢迎提交puul request~
