### ISSUE TITLE
希望能有不把下划线转驼峰的选项

### ISSUE THREAD

**Issue by rainelzhang** [moshowgame/SpringBootCodeGenerator#35]
希望能有不把下划线转驼峰的选项

**Comment by ThorinGondor** [comment]
SQL下划线转Java驼峰是标准的写法

**Comment by youngking28** [comment]
> SQL下划线转Java驼峰是标准的写法

还有很多无可奈何的因素导致实体类也是下划线，头痛

**Comment by youngking28** [comment]
> 希望能有不把下划线转驼峰的选项

已添加pr，等关主merge

**Comment by moshowgame** [comment]
> > 希望能有不把下划线转驼峰的选项
> 
> 已添加pr，等关主merge

棒棒的！已Merge
