### ISSUE TITLE
unique_request_id  列 生成 jpa entity 时候 该字段没生成出来

### ISSUE THREAD

**Issue by isLiNai** [moshowgame/SpringBootCodeGenerator#36]

**Comment by moshowgame** [comment]
你好，包含constraint/unique/using/primary/storage/pctincrease/buffer_pool/tablespace的关键字都会被过滤。。。
`boolean specialFlag=(!columnLine.contains("key ")&&!columnLine.contains("constraint")&&!columnLine.contains("using")&&!columnLine.contains("unique")
                        &&!(columnLine.contains("primary")&&columnLine.indexOf("storage")+3>columnLine.indexOf("("))
                        &&!columnLine.contains("pctincrease")
                        &&!columnLine.contains("buffer_pool")&&!columnLine.contains("tablespace")`
