### ISSUE TITLE
SQL 生成 mapper 接口，和 xml 有问题

### ISSUE THREAD

**Issue by caojiantao** [moshowgame/SpringBootCodeGenerator#41]
1、条件语句 where 是 `id_` = #{}，怎么多了下划线？
2、生成的 mapper 接口查询是 load，但是 xml 中是 selectByPrimaryKey？
3、mapper 中新增、修改，不用加 @Param 注解，否则对应 xml 解析有问题。

**Comment by moshowgame** [comment]
20190910 | 1.修复mapper接口load方法，但是xml中方法不匹配问题 2.移除mapper中CRUD时的@param 注解，会影响xml的解析（感谢@caojiantao的反馈）。3.优化MyBatis的xml文件对Oracle的支持。（感谢@wylove1992的反馈） 4.新增对boolean的处理（感谢@violinxsc的反馈）以及优化tinyint类型生成boolean类型问题（感谢@hahaYhui的反馈）
-- | --
