### ISSUE TITLE
bean类型Integer为null在fastjson不能正确解析，改成int会不会好点?

### ISSUE THREAD

**Issue by lydat** [moshowgame/SpringBootCodeGenerator#44]

**Comment by moshowgame** [comment]
是的，不过怎么说Integer可以支持一些Null的情况，这个看个人使用情况，也可以加以下注解进行转换，如果是null会自动转成0
`@JSONField(serialzeFeatures=SerializerFeature.WriteNullNumberAsZero)
Integer xxxx`
