### ISSUE TITLE
根据sql语句生成mybatis的xml语句

### ISSUE THREAD

**Issue by SomeJoker** [moshowgame/SpringBootCodeGenerator#45]
我在生产中一般会先把写好的sql通过navicat去做下验证，然后根据这个验证好的sql改写成xml，如果能直接根据写好的sql生产xml，能提高不少效率。

**Comment by liangbintao** [comment]
+1

**Comment by moshowgame** [comment]
能否提供一下模板

**Comment by moshowgame** [comment]
> 我在生产中一般会先把写好的sql通过navicat去做下验证，然后根据这个验证好的sql改写成xml，如果能直接根据写好的sql生产xml，能提高不少效率。

提供一下模板谢谢！~
