### ISSUE TITLE
生成的实体有时候会漏字段，建表语句如下

### ISSUE THREAD

**Issue by liujiansgit** [moshowgame/SpringBootCodeGenerator#47]
CREATE TABLE `py_invest_trust` (
  `date` date NOT NULL COMMENT '日期',
  `type` tinyint(4) NOT NULL COMMENT '类型:1.周2.月3.季 4.年',
  `security_invest` decimal(20,4) DEFAULT NULL COMMENT '投资:单位万元',
  `primary_market` decimal(20,4) DEFAULT NULL COMMENT '一级市场:单位万元',
  `primary_market_ratio` decimal(6,2) DEFAULT NULL COMMENT '一级市场占比:单位%',
  PRIMARY KEY (`date`,`type`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='xxxx';

**Comment by moshowgame** [comment]
hi,新版已经优化！~
