### ISSUE TITLE
column名字有时会用驼峰，不要把驼峰转换成小写

### ISSUE THREAD

**Issue by LHandCY** [moshowgame/SpringBootCodeGenerator#49]

**Comment by dhjz** [comment]
+1

**Comment by moshowgame** [comment]
> _No description provided._



> +1

HI，两位亲能否提供一下sql语句

**Comment by LHandCY** [comment]
CREATE TABLE `test1` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `userId` int(11) DEFAULT NULL,
  `userName` varchar(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;
例如这种，生成的java代码会把驼峰变成小写

**Comment by moshowgame** [comment]
sorry现在才回复，暂不支持，因为数据库字段是不建议使用驼峰的，建议下划线，加上程序一开始就是全部转换为小写字母来处理，所以会丢失对驼峰字段的处理。后续会考虑加入一些机制来调整，感谢反馈！
