### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by gaohanghang** [moshowgame/SpringBootCodeGenerator#50]
是否可以在 textArea 上面加一个复制代码的按钮，方便复制代码

简单示意图：

![image](https://user-images.githubusercontent.com/20310190/67614009-9fae0a00-f7e7-11e9-97a0-c2d0306ec5ce.png)

**Comment by moshowgame** [comment]
新版即将实现，这两天发布

**Comment by gaohanghang** [comment]
🐂🐂
