### ISSUE TITLE
代码报错了,看下控制台吧

### ISSUE THREAD

**Issue by dao-jishi** [moshowgame/SpringBootCodeGenerator#53]

**Comment by moshowgame** [comment]
你好，是公共css cdn挂了导致，后来发现正常了。

**Comment by dao-jishi** [comment]
可以,这个用着还是很舒服的,挂了后,都是到Firefox上访问才能SQL转bean

在 2019-11-13 21:47:37，"Moshow郑锴" <notifications@github.com> 写道：


你好，是公共css cdn挂了导致，后来发现正常了。
