### ISSUE TITLE
sql转实体好像卡住了，无法生成

### ISSUE THREAD

**Issue by shawntao19** [moshowgame/SpringBootCodeGenerator#55]
http://java.bejson.com/generator/?tdsourcetag=s_pctim_aiomsg
sql转实体好像卡住了，无法生成
在ie可以，chrome 78.0.3904.70点击生成按钮后无法弹出

**Comment by ddzzov** [comment]
看下是不是开了广告拦截之类的插件，我把它关掉就OK了

**Comment by moshowgame** [comment]
你好，是公共css cdn挂了导致，后来发现正常了。
