### ISSUE TITLE
你好,我是来申报BUG的-----MyBatis自动生成代码的BUG

### ISSUE THREAD

**Issue by 88888888888888888888** [moshowgame/SpringBootCodeGenerator#56]
http://java.bejson.com/generator/
这个地址中的Mybatis自动代码生成中,其中insert的sql有问题;
![image](https://user-images.githubusercontent.com/34368089/68186289-bec64c00-ffde-11e9-8f7c-9d5edd0aa570.png)
不知道能不能让你看到图片;
如果不能,我用文字描述;在Mybatis这一行中的Mybatis的table页下,有一个insert的Sql语句,他有个功能是自动返回ID,但是这里自动生成的Insert语句里面缺少了一个属性 keyProperty="id",所以,你生成的代码中是不能正常的返回自增ID的,因为缺少了 keyProperty="id"这个字段

**Comment by moshowgame** [comment]
ok。新版加上
