### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by 601404501** [moshowgame/SpringBootCodeGenerator#57]

**Comment by waynewang6660** [comment]
老板带着小姨子跑了？

**Comment by moshowgame** [comment]
hi，新版已经移除layer并改为jquery-toast，，，layer被太多广告平台使用了

**Comment by waynewang6660** [comment]
关掉广告拦截 可以用 谢谢 准备集成到项目中 很棒 一直在用 谢谢up主

**Comment by moshowgame** [comment]
> 关掉广告拦截 可以用 谢谢 准备集成到项目中 很棒 一直在用 谢谢up主

谢谢使用，新版已经上线，有什么想法欢迎提PR
