### ISSUE TITLE
广告插件拦截了 http://cdn.staticfile.org/layer/2.3/layer.js 

### ISSUE THREAD

**Issue by yonhonai** [moshowgame/SpringBootCodeGenerator#58]
广告插件拦截了 http://cdn.staticfile.org/layer/2.3/layer.js
<img width="1438" alt="截屏2019-11-22下午4 54 46" src="https://user-images.githubusercontent.com/22446229/69411994-01ab5200-0d49-11ea-9d5b-457120462339.png">

**Comment by moshowgame** [comment]
hi，新版已经移除layer并改为jquery-toast，，，layer被太多广告平台使用了
