### ISSUE TITLE
在线生成的怎么和仓库不一致?在线的目前无法体验,麻烦大佬看下,谢谢

### ISSUE THREAD

**Issue by wedtlcy** [moshowgame/SpringBootCodeGenerator#62]

**Comment by moshowgame** [comment]
被广告过滤了layer，建议下载代码生成本地运行




   POWERED BY CORE IWIN , 
              MR.MOSHOW IS LOADING THE DREAM。


 【 Moshow Core System 2017 】


◢公司：IT@汤臣倍健by-health.com
◢扣扣：804461110
◢油箱：MoshowGame@126.Com
◢围博：http://WeiBo.Com/804461110
在2019年11月25日 17:13，wedtlcy 写道：

**Comment by moshowgame** [comment]
新版已经上线并修复过滤问题
