### ISSUE TITLE
jpa 的生成entity ，新增swagger注解、SQL字段注解

### ISSUE THREAD

**Issue by yjq907** [moshowgame/SpringBootCodeGenerator#64]

**Comment by moshowgame** [comment]
> _No description provided._

麻烦提供一下模板

**Comment by yjq907** [comment]
@Entity
@Data
@Table(name="t_study_teacher")
public class TStudyTeacher implements Serializable {
    private static final long serialVersionUID = 13433425L;
    @Id
    @GeneratedValue
    @ApiModelProperty("教员id")
    @Column(name = "id")
    private Integer id;

    @ApiModelProperty("手机号")
    @Column(name = "phone_no")
    private String phoneNo;

    @ApiModelProperty("密码")
    @Column(name = "password")
    private String password;

    @ApiModelProperty("姓名")
    @Column(name = "username")
    private String username;

    @ApiModelProperty("头像图片地址")
    @Column(name = "head_img")
    private String headImg;

    @ApiModelProperty("性别，0为女，1为男")
    @Column(name = "gender")
    private Integer gender;

    @ApiModelProperty("生日，格式为yyyy-mm-dd")
    @Column(name = "birthday")
    private String birthday;

    @ApiModelProperty("个性签名")
    @Column(name = "signature")
    private String signature;

    @ApiModelProperty("所属大学")
    @Column(name = "university")
    private String university;

    @ApiModelProperty("所属专业")
    @Column(name = "major")
    private String major;

    @ApiModelProperty("学历，所教育程度")
    @Column(name = "educ")
    private String educ;

    @ApiModelProperty("学情备注")
    @Column(name = "educ_remark")
    private String educRemark;

    @ApiModelProperty("住址所在省份")
    @Column(name = "province")
    private String province;

    @ApiModelProperty("住址所在城市")
    @Column(name = "city")
    private String city;

    @ApiModelProperty("住址所在区县")
    @Column(name = "district")
    private String district;

    @ApiModelProperty("详细地址")
    @Column(name = "address")
    private String address;

    @ApiModelProperty("个人简介")
    @Column(name = "description")
    private String description;

    @ApiModelProperty("vip等级")
    @Column(name = "vip_level")
    private Integer vipLevel;

    @ApiModelProperty("状态，0为无效，1为有效")
    @Column(name = "state")
    private Integer state;
}






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Moshow郑锴"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 晚上11:09
收件人:&nbsp;"moshowgame/SpringBootCodeGenerator"<SpringBootCodeGenerator@noreply.github.com&gt;;
抄送:&nbsp;"龘Ψ"<907084253@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [moshowgame/SpringBootCodeGenerator] jpa 的生成entity ，新增swagger注解、SQL字段注解 (#64)



 
No description provided.
  
麻烦提供一下模板

**Comment by moshowgame** [comment]
已整合~
