### ISSUE TITLE
_min结尾字段少字重大Bug！！！

### ISSUE THREAD

**Issue by livejava** [moshowgame/SpringBootCodeGenerator#65]
![image](https://user-images.githubusercontent.com/44918548/69946548-c5d17300-1526-11ea-887b-fcfb035520b9.png)
![image](https://user-images.githubusercontent.com/44918548/69946589-da157000-1526-11ea-854d-af3f0fd4b134.png)
buy_min 等 以  _min结尾的字段，生成后，都少了最后的   n   !!!!!

**Comment by moshowgame** [comment]
hi。这个上次已经修复，404的问题三叔已经搞定，现在可以访问了
