### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by A2Data** [moshowgame/SpringBootCodeGenerator#66]
CREATE TABLE 'lab_model_evaluation' (
  'id' int(11) NOT NULL AUTO_INCREMENT,
  'advertiser' varchar(50) DEFAULT NULL,
  'model' varchar(50) DEFAULT NULL,
  'model_type' varchar(50) DEFAULT NULL,
  'removed' tinyint(1) DEFAULT NULL,
  'creation' datetime DEFAULT NULL,
  'last_modified' datetime DEFAULT NULL,
  'version' int(11) DEFAULT NULL,
  'index_sign' tinyint(1) NOT NULL DEFAULT 0,
  'index_name' varchar(20) DEFAULT NULL,
  'index_value' float DEFAULT NULL,
  'index_placeholder1' varchar(20) DEFAULT NULL,
  'figure_sign' tinyint(1) NOT NULL DEFAULT 0,
  'figure_name' varchar(20) DEFAULT NULL,
  'figure_series' varchar(20) DEFAULT NULL,
  'figure_type' varchar(20) DEFAULT NULL,
  'figure_is_x_float' tinyint(1) DEFAULT NULL,
  'figure_x' varchar(20) DEFAULT NULL,
  'figure_y' float DEFAULT NULL,
  'figure_xname' varchar(20) DEFAULT NULL,
  'figure_yname' varchar(20) DEFAULT NULL,
  'figure_placeholder1' varchar(20) DEFAULT NULL,
  'figure_placeholder2' varchar(20) DEFAULT NULL,
  'feature_sign' tinyint(1) NOT NULL DEFAULT 0,
  'feature_name' varchar(100) DEFAULT NULL,
  'feature_is_positive' tinyint(1) DEFAULT NULL,
  'feature_importance' float DEFAULT NULL,
  'feature_shap' float DEFAULT NULL,
  'feature_shuffle' float DEFAULT NULL,
  'feature_lost' float DEFAULT NULL,
  'feature_bs' float DEFAULT NULL,
  'feature_placeholder1' varchar(20) DEFAULT NULL,
  'feature_placeholder2' varchar(20) DEFAULT NULL,
  PRIMARY KEY ('id')
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by A2Data** [comment]
不能识别

**Comment by moshowgame** [comment]
> 不能识别

hi，之前可能有问题。现在验证了一下，已经ok，如果有什么个别字段有问题，可以发出来。
