### ISSUE TITLE
bejson的页面404了

### ISSUE THREAD

**Issue by umgsai** [moshowgame/SpringBootCodeGenerator#67]
http://java.bejson.com/generator/

**Comment by moshowgame** [comment]
是的，404了不知道是不是服务不稳定。已经跟三叔说了




   POWERED BY CORE IWIN , 
              MR.MOSHOW IS LOADING THE DREAM。


 【 Moshow Core System 2017 】


◢公司：IT@汤臣倍健by-health.com
◢扣扣：804461110
◢油箱：MoshowGame@126.Com
◢围博：http://WeiBo.Com/804461110
在2019年12月05日 17:36，商商 写道：

http://java.bejson.com/generator/

**Comment by moshowgame** [comment]
hi。三叔已经修复，现在可以访问了
