### ISSUE TITLE
tinyint无法自定义转换类型，命名会自动转换

### ISSUE THREAD

**Issue by Muceball** [moshowgame/SpringBootCodeGenerator#68]
tinyint类型能手动选择转换类型就好了，然后命名问题必须要选择一种，但是我这边不需要转换！希望加个不处理的

**Comment by moshowgame** [comment]
sorry.现在才回复，|20191115|1.添加tinyint类型转换(感谢@lixiliang&@liujiansgit的Suggestion)。新版已经支持、
