### ISSUE TITLE
生成entity出现bug

### ISSUE THREAD

**Issue by smilexzh** [moshowgame/SpringBootCodeGenerator#70]
如果表的字段名包含 date 的话，生成的类型就会是 Date 类型。如：

![image](https://user-images.githubusercontent.com/42776624/71332694-1e1df280-2572-11ea-8f08-7f7395bbaf3f.png)

这里的更新人应该生成的是String类型，结果生成的是Date类型

![image](https://user-images.githubusercontent.com/42776624/71332739-4574bf80-2572-11ea-9b08-6ca55dd3558f.png)

是不是可以先通过正则匹配获取字段类型之后再转换呢

**Comment by moshowgame** [comment]
fixed.
