### ISSUE TITLE
pgsql Sql生成有问题。直接服务器出错。

### ISSUE THREAD

**Issue by 1808083642** [moshowgame/SpringBootCodeGenerator#72]
sql dll 文件如下：
CREATE TABLE "public"."app_column_properties" (
  "id" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "status" char(1) COLLATE "pg_catalog"."default",
  "creator_id" varchar(100) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6),
  "modifyier_id" varchar(100) COLLATE "pg_catalog"."default",
  "modify_time" timestamp(6),
  "field_name" varchar(32) COLLATE "pg_catalog"."default",
  "field_code" varchar(32) COLLATE "pg_catalog"."default",
  "is_show" char(1) COLLATE "pg_catalog"."default",
  "business_type" varchar(32) COLLATE "pg_catalog"."default",
  "field_seq" numeric(20),
  CONSTRAINT "pk_app_column_properties" PRIMARY KEY ("id")
)
;

ALTER TABLE "public"."app_column_properties" 
  OWNER TO "postgres";

COMMENT ON TABLE "public"."app_column_properties" IS '属性设置表';

**Comment by moshowgame** [comment]
bejson.com开启了安全防护策略。您刚才的操作被安全防护策略禁止，可能的操作是：提交某个语句、SQL命令、异常数据提交等。

====
估计是最近bejson开启了某些策略，status和is_show字段不知道怎么就被禁止了。。

建议下载jar包自己运行，或者本地启动项目
