### ISSUE TITLE
时间自动识别错误,字段里面有时间类型的会识别为时间类型

### ISSUE THREAD

**Issue by cnlw** [moshowgame/SpringBootCodeGenerator#76]
![image](https://user-images.githubusercontent.com/38176240/71660247-5ea51980-2d85-11ea-8d99-eec54e4d1257.png)

**Comment by cnlw** [comment]
![image](https://user-images.githubusercontent.com/38176240/71660310-9c09a700-2d85-11ea-8ea7-531195361f58.png)

**Comment by zomgit** [comment]
出现了相同问题。oracle数据库，字段名是 xxxTimes，类型是NUMBER(16)，DTO直接给我转成了date类型,郁闷。
The same problem occurred. The oracle database, the field name is xxxTimes, the type is NUMBER (16), DTO converted to date type. depressed.

**Comment by moshowgame** [comment]
CREATE TABLE 'userinfo' (
  'user_id' int(11) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  'user_name' varchar(255) NOT NULL COMMENT '用户名',
  'xxxTimes' number(16) NOT NULL COMMENT '创建时间',
  PRIMARY KEY ('user_id')
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息'
        
最新版已经修复过了，生成为：

    /**
    * 创建时间
    */
    private Long xxxtimes;
