### ISSUE TITLE
sql生成jpa的实体可以不带swagger的注解吗，还有@Column注解的参数必须加上name

### ISSUE THREAD

**Issue by liuyu-struggle** [moshowgame/SpringBootCodeGenerator#77]
sql生成jpa的实体可以不带swagger的注解吗，还有@Column注解的参数必须加上name,
现在@Column注解的参数不加name会报错，而且一般情况下实体类上的swagger可以不可以不加呀，或者可选择性（让用户自己选择添加再添加）的添加。 @moshowgame

**Comment by xiaozhiliaoo** [comment]
我也遇到这个问题。

**Comment by moshowgame** [comment]
Fixed.已增加swagger-ui开关设置
