### ISSUE TITLE
comment 关键字识别问题

### ISSUE THREAD

**Issue by 1nchaos** [moshowgame/SpringBootCodeGenerator#80]
建表语句如下：
CREATE TABLE `comment_base_info` (
  `comment_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '注释id',
  `comment_type` tinyint(4) DEFAULT NULL COMMENT '注释类型:1.题目注释;2.问卷说明;3.题目大类说明;',
  `content` text COMMENT '内容',
  `creator` varchar(45) DEFAULT NULL COMMENT '创建人',
  `status` tinyint(4) DEFAULT '1' COMMENT '状态:0.删除;1.正常',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`comment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='注释信息表';

生成实体的注解有点问题
/**
    * _id int(11)
    */
    private Integer commentId;

    /**
    * _type tinyint(4)
    */
    private boolean commentType;

**Comment by moshowgame** [comment]
感谢你的反馈，已fix，修复的有点晚，请见谅
