### ISSUE TITLE
Jpa 踩坑记录与 lombok 配合使用的问题

### ISSUE THREAD

**Issue by deux-ex** [moshowgame/SpringBootCodeGenerator#84]
与 lombok 配合使用的问题
如果 Entity 直接使用 @Data 注解的话，如果 Entity 之间存在关联关系，则会产生 StackOverflow 的问题。

产生这个问题的原因是 lombok 默认自动生成的 toString() 方法和 hashCode 方法会产生循环依赖。

解决方案就是只用 @Getter、@Setter 注解，然后自己重写 toString() 和 hashCode 方法。或者使用 @EqualsAndHashCode 注解时，在依赖的被维护端字段加上 @EqualsAndHashCode.Exclude 注解，也就是凡是关系注解里有 mappedBy 的都要加上 @EqualsAndHashCode.Exclude。

参考文档：

使用Hibernate、JPA、Lombok遇到的有趣问题
Lombok.hashCode issue with “java.lang.StackOverflowError: null”
@EqualsAndHashCode

https://blog.qxzzf.com/spring-boot-jpa-try-out
https://juejin.im/post/5b3ca5386fb9a04fd34370d2

**Comment by moshowgame** [comment]
can reslove it by adding: 
@EqualsAndHashCode(exclude="frameworkSortingType") and @JsonManagedReference and @JsonBackReference

-----
亲，关于这个循环依赖的问题，其实有其他的解决方案。你说的也是其中的一种。可以试下3.0版本的无lombok模式（set&get），也可以降级或者升级lombok到最新版本，还可以使用以上注解。
