### ISSUE TITLE
外键识别错误

### ISSUE THREAD

**Issue by tornadoorz** [moshowgame/SpringBootCodeGenerator#9]
CREATE TABLE `relations_role_permission` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增长主键',
  `role_id` int(11) NOT NULL COMMENT '角色id',
  `permission_id` int(11) NOT NULL COMMENT '权限id',
  PRIMARY KEY (`id`),
  KEY `FK_permission_id` (`permission_id`),
  KEY `FK_role_id` (`role_id`),
  CONSTRAINT `FK_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `permission` (`id`),
  CONSTRAINT `FK_role_id` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色与权限关联表';

生成的 JPA - Entity 时,多了两个key变量

    /**
    * key
    */
    private String key;

    /**
    * key
    */
    private String key;

**Comment by moshowgame** [comment]
> CREATE TABLE

感谢反馈，已经修复
