### ISSUE TITLE
tinyint类型生成的实体类型错误

### ISSUE THREAD

**Issue by Lsep** [moshowgame/SpringBootCodeGenerator#98]
表结构如下
![sql](https://user-images.githubusercontent.com/20450793/97693544-4b192b00-1adc-11eb-98aa-6211f8b3c1a1.png)
生成的实体如下
![entity](https://user-images.githubusercontent.com/20450793/97693627-6a17bd00-1adc-11eb-846a-759236642ff3.png)
**多次试验后发现只要字段包含`time`，tinyint生成的实体类型都是Date**

**Comment by moshowgame** [comment]
3.0版本已通过改变判断的顺序修复该问题，感谢反馈，thanks！
